name: Run

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run-ts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript with ts-node
        run: npx ts-node index.ts
        env:
          GUILD: ${{ secrets.GUILD }}
          CATEGORY: ${{ secrets.CATEGORY }}
          TOKEN: ${{ secrets.TOKEN }}
